name: leancode_chat_client
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.2"

dependencies:
  clock: ^1.1.2
  cloud_firestore: ^5.5.0
  collection: ^1.19.1
  cqrs: ^10.0.2
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.20.5
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  leancode_contracts: ^0.8.0
  logging: ^1.3.0
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.9.5
  leancode_contracts_generator: ^0.17.0
  leancode_lint: ^17.0.0
  mocktail: ^1.0.4
  test: ^1.25.8

flutter:
  plugin:
    platforms:
      android:
        package: pl.leancode.leancode_chat_client
        pluginClass: LeancodeChatClientPlugin
      ios:
        pluginClass: LeancodeChatClientPlugin
